name: health_nest
description: A comprehensive health and fitness application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  pedometer: ^4.1.1
  intl: ^0.20.2
  fl_chart: ^1.0.0
  http: ^1.1.2
  google_maps_flutter: ^2.5.3
  location: ^8.0.1
  cached_network_image: ^3.4.1
  gemini: ^2.1.1
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.5
  lottie: ^3.0.0
  flutter_spinkit: ^5.2.0
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.1.0
  animate_do: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/documents/
    - assets/fonts/
    - .env
    - assets/data/exercises.json # This line has been changed

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700